DROP DATABASE IF EXISTS barkfeed_db;
CREATE DATABASE barkfeed_db;

USE barkfeed_db;

CREATE TABLE Content (
  ContentID INT(11) NOT NULL AUTO_INCREMENT,
  PostID INT(11) NOT NULL,
  Title VARCHAR(45) DEFAULT NULL,
  Content VARCHAR(45) DEFAULT NULL,
  AddDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Deleted TINYINT(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (ContentID, PostID)
);

CREATE TABLE User (
  UserID INT(11) NOT NULL AUTO_INCREMENT,
  Username VARCHAR(45) NOT NULL,
  Password VARCHAR(45) NOT NULL,
  Content VARCHAR(45) DEFAULT NULL,
  AddDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Deleted TINYINT(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (UserID)
);

CREATE TABLE PostType (
  PostTypeID INT(11) NOT NULL AUTO_INCREMENT,
  Type VARCHAR(45) NOT NULL,
  PRIMARY KEY (PostTypeID)
);

CREATE TABLE Post (
  PostID INT(11) NOT NULL AUTO_INCREMENT,
  UserID INT(11) NOT NULL,
  PostTypeID INT(11) NOT NULL,
  ParentID INT(11) NULL DEFAULT NULL,
  AddDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Deleted TINYINT(4) NOT NULL DEFAULT 0,
  Content_ContentID INT(11) NOT NULL,
  Content_PostID INT(11) NOT NULL,
  PRIMARY KEY (PostID, Content_ContentID, Content_PostID)
);


